services:
  php:
    build: ./docker/php
    container_name: fishing_area_php
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_DATABASE=fishing_area_db
      - DB_USERNAME=fishing_user
      - DB_PASSWORD=fishing_pass

  nginx:
    image: nginx:stable-alpine
    container_name: fishing_area_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: fishing_area_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fishing_area_db
      MYSQL_USER: fishing_user
      MYSQL_PASSWORD: fishing_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  front:
    image: node:21
    container_name: fishing_area_front
    working_dir: /var/www/front
    volumes:
      - ./front:/var/www/front
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - php

volumes:
  db_data:
